Fix: set empty description if not set
wikifactory/import-export pull request #69
Opened 2021-03-12 14:04 UTC by rievo

Now, if the "description" field of the folder is not set in google drive, we default to an empty string

2021-03-12 15:02 UTC, drewler requested changes
Please add a test case repoducing how it crashed before. This way, we'll lower the chances of reintroducing the bug.

2021-03-12 15:04 UTC, drewler commented on app/importers/google_drive.py
> +        )
```suggestion
        manifest_input.project_description = self.root_item.get("description", "")
```

2021-03-22 17:04 UTC, drewler approved these changes

2021-03-22 17:39 UTC, squeaky-pl approved these changes

2021-03-22 17:39 UTC, merged