Added the Git exporter
wikifactory/import-export pull request #90
Opened 2021-04-28 10:33 UTC by rievo

2021-05-13 08:08 UTC, squeaky-pl requested changes

2021-05-13 08:08 UTC, squeaky-pl commented on app/exporters/git.py
> +        except subprocess.CalledProcessError:
```suggestion
        except subprocess.CalledProcessError as e:
```

2021-05-13 08:08 UTC, squeaky-pl commented on app/exporters/git.py
> +            raise GitRemoteOriginError("Found an error while setting the remote origin")
```suggestion
            raise GitRemoteOriginError("Found an error while setting the remote origin") from e
```

2021-05-13 08:08 UTC, squeaky-pl commented on app/exporters/git.py
> +        except subprocess.CalledProcessError:
```suggestion
        except subprocess.CalledProcessError as e:
```

2021-05-13 08:08 UTC, squeaky-pl commented on app/exporters/git.py
> +            raise GitPushError("Error pushing to origin/main")
```suggestion
            raise GitPushError("Error pushing to origin/main") from e
```

2021-05-26 07:55 UTC, drewler commented on app/service_validators/services.py
> +        r"^https?:\/\/(www\.)?git(?P<service>hub|lab)\.com\/(?P<user>[\w-]+)/(?P<project>[\w-]+)"
Guess even if not 100% accurate, `user` is better than `organization`

2021-05-27 15:15 UTC, squeaky-pl approved these changes

2021-06-04 07:40 UTC, merged