Integrate the Dropbox Exporter
wikifactory/import-export pull request #91
Opened 2021-05-12 07:33 UTC by rievo

With the implementation as is, the user can export to a home-based Dropbox URL (e.g. https://www.dropbox.com/home/testfolder). For the moment, it is not possible to export towards a shared link

2021-05-13 08:03 UTC, squeaky-pl requested changes

2021-05-13 08:03 UTC, squeaky-pl commented on app/exporters/dropbox.py
> +        except ApiError:
```suggestion
        except ApiError as e:
```

2021-05-13 08:03 UTC, squeaky-pl commented on app/exporters/dropbox.py
> +            raise FileUploadFailed(f"Error uploading file: {local_path}")
```suggestion
            raise FileUploadFailed(f"Error uploading file: {local_path}") from e
```

2021-05-13 08:03 UTC, squeaky-pl commented on app/exporters/dropbox.py
> +        except ValidationError:
```suggestion
        except ValidationError as e:
```

2021-05-13 08:03 UTC, squeaky-pl commented on app/exporters/dropbox.py
> +            )
```suggestion
            ) from e
```

2021-05-14 08:28 UTC, squeaky-pl requested changes

2021-05-14 08:28 UTC, squeaky-pl commented on app/exporters/dropbox.py
> +            return
This is unreachable code
```suggestion
         
```

2021-05-26 07:57 UTC, drewler commented
I'll look into why the shared links don't work correcly. Maybe that's just how it works and there's no fix, but I'll take a last look either way.

If everything else works, we'll probably merge anyway as this could be dealt with on a separate PR.

2021-05-27 15:17 UTC, squeaky-pl approved these changes

2021-06-02 07:27 UTC, drewler approved these changes
Looks good to me. Let's merge this one and I'll try to implement support for "shared link" URL format on a separate PR

2021-06-04 08:12 UTC, merged